#!/bin/bash

# Check if qpdf is installed
if ! command -v qpdf &> /dev/null; then
  echo "Installing qpdf..."
  brew install qpdf
fi

# Create a temporary directory for intermediate files
mkdir -p temp

# Convert each PNG to a PDF using sips
for png in diagrams/*.png; do
  filename=$(basename "$png" .png)
  sips -s format pdf "$png" --out "temp/${filename}.pdf"
done

# Add titles to each PDF using qpdf
for pdf in temp/*.pdf; do
  filename=$(basename "$pdf" .pdf)
  qpdf --linearize --replace-input --update-info-json <(echo "{\"Title\": \"${filename}\", \"Author\": \"Generated by diagrams_to_pdf.sh\"}") "$pdf"
done

# Combine all PDFs into a single file
/System/Applications/Preview.app/Contents/MacOS/Preview -p "temp"/*.pdf -o all_diagrams.pdf

# Clean up temporary files
rm -rf temp

echo "Created all_diagrams.pdf with all diagrams!" 