// Field aliases for enhanced natural language query processing
// Auto-generated from actual endpoint data fields and enhanced with comprehensive AI-generated synonyms
// Generated: 2025-08-11T19:47:59.201Z (Base) + AI-Enhanced: 2025-08-11T21:30:00.000Z
// Total fields: 132 from 25 endpoints
// Total aliases: 400+ natural language terms for superior user experience
export const FIELD_ALIASES: Record<string, string> = {
  // === SYSTEM FIELDS ===
  "creation date": "CreationDate",
  "created": "CreationDate",
  "date created": "CreationDate",
  "when created": "CreationDate",
  "created on": "CreationDate",
  "creation time": "CreationDate",
  "creator": "Creator",
  "created by": "Creator",
  "author": "Creator",
  "made by": "Creator",
  "originator": "Creator",
  "description": "DESCRIPTION",
  "area description": "DESCRIPTION",
  "area info": "DESCRIPTION",
  "area details": "DESCRIPTION",
  "zip code": "DESCRIPTION",
  "postal code area": "DESCRIPTION",
  "location info": "DESCRIPTION",
  "place description": "DESCRIPTION",
  "area name": "DESCRIPTION",
  "edit date": "EditDate",
  "edited": "EditDate",
  "last modified": "EditDate",
  "updated": "EditDate",
  "modified date": "EditDate",
  "last updated": "EditDate",
  "editor": "Editor",
  "edited by": "Editor",
  "modified by": "Editor",
  "updated by": "Editor",
  "last editor": "Editor",
  "id": "ID",
  "identifier": "ID",
  "area id": "ID",
  "unique id": "ID",
  "record id": "ID",
  "object id": "OBJECTID",
  "objectid": "OBJECTID",
  "object identifier": "OBJECTID",
  "esri object id": "OBJECTID",
  "shape area": "Shape__Area",
  "area": "Shape__Area",
  "geographic area": "Shape__Area",
  "polygon area": "Shape__Area",
  "size": "Shape__Area",
  "area size": "Shape__Area",
  "square footage": "Shape__Area",
  "coverage": "Shape__Area",
  "shape length": "Shape__Length", 
  "length": "Shape__Length",
  "perimeter": "Shape__Length",
  "boundary length": "Shape__Length",
  "border length": "Shape__Length",
  "outline": "Shape__Length",
  "circumference": "Shape__Length",
  "thematic value": "thematic_value",
  "internal": "thematic_value",
  "theme value": "thematic_value",
  "classification": "thematic_value",

  // === ANALYSIS SCORE FIELDS ===
  "algorithm agreement score": "algorithm_agreement_score",
  "algorithm agreement": "algorithm_agreement_score",
  "model agreement": "algorithm_agreement_score",
  "ai agreement": "algorithm_agreement_score",
  "consensus": "algorithm_agreement_score",
  "algorithm performance score": "algorithm_performance_score",
  "algorithm performance": "algorithm_performance_score",
  "model performance": "algorithm_performance_score",
  "ai performance": "algorithm_performance_score",
  "analysis score": "analysis_score",
  "analysis": "analysis_score",
  "analytical score": "analysis_score",
  "evaluation": "analysis_score",
  "assessment": "analysis_score",
  "anomaly detection score": "anomaly_detection_score",
  "anomaly detection": "anomaly_detection_score",
  "outlier identification": "anomaly_detection_score",
  "unusual patterns": "anomaly_detection_score",
  "aberration detection": "anomaly_detection_score",
  "deviation detection": "anomaly_detection_score",
  "anomaly insight score": "anomaly_insight_score",
  "anomaly insights": "anomaly_insight_score",
  "unusual insights": "anomaly_insight_score",
  "outlier insights": "anomaly_insight_score",
  "anomaly performance score": "anomaly_performance_score",
  "anomaly performance": "anomaly_performance_score",
  "outlier performance": "anomaly_performance_score",
  "anomaly score": "anomaly_score",
  "anomaly": "anomaly_score",
  "unusual": "anomaly_score",
  "aberrant": "anomaly_score",
  "deviant": "anomaly_score",
  "brand difference score": "brand_difference_score",
  "brand difference": "brand_difference_score",
  "brand gap": "brand_difference_score",
  "brand variance": "brand_difference_score",
  "competitive difference": "brand_difference_score",
  "cluster performance score": "cluster_performance_score",
  "cluster performance": "cluster_performance_score",
  "grouping performance": "cluster_performance_score",
  "clustering quality": "cluster_performance_score",
  "cluster score": "cluster_score",
  "cluster": "cluster_score",
  "grouping": "cluster_score",
  "segmentation": "cluster_score",
  "group": "cluster_score",
  "comparative score": "comparative_score",
  "comparative": "comparative_score",
  "comparison": "comparative_score",
  "relative": "comparative_score",
  "versus": "comparative_score",
  "comparison score": "comparison_score",
  "competitive advantage score": "competitive_advantage_score",
  "competitive advantage": "competitive_advantage_score",
  "market advantage": "competitive_advantage_score",
  "business advantage": "competitive_advantage_score",
  "edge": "competitive_advantage_score",
  "competitive score": "competitive_score",
  "competitive": "competitive_score",
  "competition": "competitive_score",
  "market competition": "competitive_score",
  "rivalry": "competitive_score",
  "consensus performance score": "consensus_performance_score",
  "consensus performance": "consensus_performance_score",
  "agreement performance": "consensus_performance_score",
  "consensus score": "consensus_score",
  "agreement": "consensus_score",
  "unified score": "consensus_score",
  "correlation score": "correlation_score",
  "correlation": "correlation_score",
  "relationship": "correlation_score",
  "association": "correlation_score",
  "connection": "correlation_score",
  "relatedness": "correlation_score",
  "correlation strength score": "correlation_strength_score",
  "correlation strength": "correlation_strength_score",
  "relationship strength": "correlation_strength_score",
  "association strength": "correlation_strength_score",
  "customer profile score": "customer_profile_score",
  "customer profile": "customer_profile_score",
  "customer analysis": "customer_profile_score",
  "user profile": "customer_profile_score",
  "client profile": "customer_profile_score",
  "demographic opportunity score": "demographic_opportunity_score",
  "demographic opportunity": "demographic_opportunity_score",
  "population opportunity": "demographic_opportunity_score",
  "market opportunity": "demographic_opportunity_score",
  "demographic potential": "demographic_opportunity_score",
  "demographic score": "demographic_score",
  "demographic": "demographic_score",
  "population score": "demographic_score",
  "people score": "demographic_score",
  "dimensionality performance score": "dimensionality_performance_score",
  "dimensionality performance": "dimensionality_performance_score",
  "dimension performance": "dimensionality_performance_score",
  "dimensionality score": "dimensionality_score",
  "dimensionality": "dimensionality_score",
  "dimension": "dimensionality_score",
  "complexity": "dimensionality_score",
  "ensemble performance score": "ensemble_performance_score",
  "ensemble performance": "ensemble_performance_score",
  "combined performance": "ensemble_performance_score",
  "ensemble strength score": "ensemble_strength_score",
  "ensemble strength": "ensemble_strength_score",
  "combined strength": "ensemble_strength_score",
  "feature importance score": "feature_importance_score",
  "feature importance": "feature_importance_score",
  "variable importance": "feature_importance_score",
  "factor importance": "feature_importance_score",
  "significance": "feature_importance_score",
  "feature interaction score": "feature_interaction_score",
  "feature interaction": "feature_interaction_score",
  "variable interaction": "feature_interaction_score",
  "factor interaction": "feature_interaction_score",
  "importance score": "importance_score",
  "importance": "importance_score",
  "priority": "importance_score",
  "significance score": "importance_score",
  "relevance": "importance_score",
  "interaction score": "interaction_score",
  "interaction": "interaction_score",
  "interplay": "interaction_score",
  "model selection performance score": "model_selection_performance_score",
  "model selection performance": "model_selection_performance_score",
  "algorithm selection performance": "model_selection_performance_score",
  "model selection score": "model_selection_score",
  "model selection": "model_selection_score",
  "algorithm selection": "model_selection_score",
  "outlier detection score": "outlier_detection_score",
  "outlier detection": "outlier_detection_score",
  "exception detection": "outlier_detection_score",
  "outlier score": "outlier_score",
  "outlier": "outlier_score",
  "exception": "outlier_score",
  "extreme value": "outlier_score",
  "performance score": "performance_score",
  "performance": "performance_score",
  "efficiency": "performance_score",
  "effectiveness": "performance_score",
  "quality": "performance_score",
  "predictive modeling score": "predictive_modeling_score",
  "predictive modeling": "predictive_modeling_score",
  "forecasting": "predictive_modeling_score",
  "prediction quality": "predictive_modeling_score",
  "predictive score": "predictive_score",
  "predictive": "predictive_score",
  "prediction": "predictive_score",
  "forecast": "predictive_score",
  "scenario analysis score": "scenario_analysis_score",
  "scenario analysis": "scenario_analysis_score",
  "scenario planning": "scenario_analysis_score",
  "what if analysis": "scenario_analysis_score",
  "scenario score": "scenario_score",
  "scenario": "scenario_score",
  "situation": "scenario_score",
  "case": "scenario_score",
  "segment profiling score": "segment_profiling_score",
  "segment profiling": "segment_profiling_score",
  "customer segmentation": "segment_profiling_score",
  "market segmentation": "segment_profiling_score",
  "segment score": "segment_score",
  "segment": "segment_score",
  "group score": "segment_score",
  "category": "segment_score",
  "sensitivity score": "sensitivity_score",
  "sensitivity": "sensitivity_score",
  "responsiveness": "sensitivity_score",
  "susceptibility": "sensitivity_score",
  "strategic score": "strategic_score",
  "strategic": "strategic_score",
  "strategy": "strategic_score",
  "business strategy": "strategic_score",
  "strategic value score": "strategic_value_score",
  "strategic value": "strategic_value_score",
  "business value": "strategic_value_score",
  "strategic importance": "strategic_value_score",
  "strategic worth": "strategic_value_score",
  "trend score": "trend_score",
  "trend": "trend_score",
  "pattern": "trend_score",
  "trajectory": "trend_score",
  "direction": "trend_score",
  "trend strength score": "trend_strength_score",
  "trend strength": "trend_strength_score",
  "pattern strength": "trend_strength_score",
  "trend intensity": "trend_strength_score",

  // === MP CODES (Consumer Financial Behavior) ===
  // MP10002: Bank of America Usage
  "mp10002a_b": "MP10002A_B",
  "mp10002a_b_p": "MP10002A_B_P",
  "mp10002": "MP10002A_B",
  "bank of america": "MP10002A_B_P",
  "boa": "MP10002A_B_P",
  "bank of america customers": "MP10002A_B_P",
  "boa users": "MP10002A_B_P",
  "bank of america bank": "MP10002A_B_P",
  "used bank of america": "MP10002A_B_P",
  "boa banking": "MP10002A_B_P",
  
  // MP10020: Savings Account Ownership
  "mp10020a_b": "MP10020A_B", 
  "mp10020a_b_p": "MP10020A_B_P",
  "mp10020": "MP10020A_B",
  "savings account": "MP10020A_B_P",
  "savings": "MP10020A_B_P",
  "have savings": "MP10020A_B_P",
  "savings account holders": "MP10020A_B_P",
  "personal savings": "MP10020A_B_P",
  "bank savings": "MP10020A_B_P",
  "savers": "MP10020A_B_P",
  "saving money": "MP10020A_B_P",
  
  // MP10028: Personal Line of Credit
  "mp10028a_b": "MP10028A_B",
  "mp10028a_b_p": "MP10028A_B_P",
  "mp10028": "MP10028A_B",
  "line of credit": "MP10028A_B_P",
  "personal line of credit": "MP10028A_B_P",
  "credit line": "MP10028A_B_P",
  "personal credit": "MP10028A_B_P",
  "have credit line": "MP10028A_B_P",
  "credit facility": "MP10028A_B_P",
  "borrowing capacity": "MP10028A_B_P",
  
  // MP10104: TurboTax Users
  "mp10104a_b": "MP10104A_B",
  "mp10104a_b_p": "MP10104A_B_P", 
  "mp10104": "MP10104A_B",
  "turbotax": "MP10104A_B_P",
  "turbo tax": "MP10104A_B_P",
  "turbotax users": "MP10104A_B_P",
  "used turbotax": "MP10104A_B_P",
  "turbotax online": "MP10104A_B_P",
  "tax software": "MP10104A_B_P",
  "online tax preparation": "MP10104A_B_P",
  "tax prep software": "MP10104A_B_P",
  "intuit users": "MP10104A_B_P",
  
  // MP10110: Apple Pay Users
  "mp10110a_b": "MP10110A_B",
  "mp10110a_b_p": "MP10110A_B_P",
  "mp10110": "MP10110A_B",
  "apple pay": "MP10110A_B_P",
  "used apple pay": "MP10110A_B_P",
  "apple pay users": "MP10110A_B_P",
  "digital payment": "MP10110A_B_P",
  "mobile payment": "MP10110A_B_P",
  "contactless payment": "MP10110A_B_P",
  "apple wallet": "MP10110A_B_P",
  "iphone payment": "MP10110A_B_P",
  "digital wallet": "MP10110A_B_P",
  
  // MP10116: Credit Card Balance Carriers
  "mp10116a_b": "MP10116A_B",
  "mp10116a_b_p": "MP10116A_B_P",
  "mp10116": "MP10116A_B",
  "credit card balance": "MP10116A_B_P",
  "carry balance": "MP10116A_B_P",
  "credit card debt": "MP10116A_B_P",
  "monthly balance": "MP10116A_B_P",
  "credit debt": "MP10116A_B_P",
  "revolving credit": "MP10116A_B_P",
  "credit utilization": "MP10116A_B_P",
  "debt carriers": "MP10116A_B_P",
  
  // MP10120: Google Pay Users
  "mp10120a_b": "MP10120A_B",
  "mp10120a_b_p": "MP10120A_B_P",
  "mp10120": "MP10120A_B",
  "google pay": "MP10120A_B_P",
  "used google pay": "MP10120A_B_P",
  "google pay users": "MP10120A_B_P",
  "google wallet": "MP10120A_B_P",
  "android payment": "MP10120A_B_P",
  "google payment": "MP10120A_B_P",
  
  // MP10128: H&R Block Users
  "mp10128a_b": "MP10128A_B",
  "mp10128a_b_p": "MP10128A_B_P",
  "mp10128": "MP10128A_B",
  "hr block": "MP10128A_B_P",
  "h&r block": "MP10128A_B_P",
  "h and r block": "MP10128A_B_P",
  "used hr block": "MP10128A_B_P",
  "hrblock": "MP10128A_B_P",
  "hr block online": "MP10128A_B_P",
  "h&r block online": "MP10128A_B_P",
  "block tax prep": "MP10128A_B_P",
  
  // MP10138: Cryptocurrency Owners
  "mp10138a_b": "MP10138A_B", 
  "mp10138a_b_p": "MP10138A_B_P",
  "mp10138": "MP10138A_B",
  "cryptocurrency": "MP10138A_B_P",
  "crypto": "MP10138A_B_P",
  "bitcoin": "MP10138A_B_P",
  "crypto investment": "MP10138A_B_P",
  "cryptocurrency investment": "MP10138A_B_P",
  "own crypto": "MP10138A_B_P",
  "crypto owners": "MP10138A_B_P",
  "digital currency": "MP10138A_B_P",
  "blockchain investment": "MP10138A_B_P",
  "crypto investors": "MP10138A_B_P",

  // === X CODES (Financial Asset Values) ===
  // X14058: Stocks/Bonds/Mutual Funds Investment Value
  "x14058_x": "X14058_X",
  "x14058_x_a": "X14058_X_A", 
  "x14058": "X14058_X",
  "stocks": "X14058_X",
  "bonds": "X14058_X",
  "mutual funds": "X14058_X",
  "investments": "X14058_X",
  "portfolio": "X14058_X",
  "securities": "X14058_X",
  "stock portfolio": "X14058_X",
  "investment portfolio": "X14058_X",
  "equity": "X14058_X",
  "equities": "X14058_X",
  "stock value": "X14058_X",
  "bond value": "X14058_X",
  "mutual fund value": "X14058_X",
  "investment value": "X14058_X",
  "securities value": "X14058_X",
  "brokerage account": "X14058_X",
  "retirement investments": "X14058_X",
  "401k": "X14058_X",
  "ira": "X14058_X",
  
  // X14060: Checking/Savings/Money Market/CDs Value
  "x14060_x": "X14060_X",
  "x14060_x_a": "X14060_X_A",
  "x14060": "X14060_X",
  "checking account": "X14060_X",
  "savings account value": "X14060_X",
  "money market": "X14060_X",
  "certificate of deposit": "X14060_X",
  "cd": "X14060_X",
  "cds": "X14060_X",
  "bank deposits": "X14060_X",
  "liquid assets": "X14060_X",
  "cash deposits": "X14060_X",
  "deposit accounts": "X14060_X",
  "bank account value": "X14060_X",
  "money market account": "X14060_X",
  "time deposit": "X14060_X",
  "cash reserves": "X14060_X",
  "emergency fund": "X14060_X",
  "liquid savings": "X14060_X",
  
  // X14068: Credit Card Debt Value
  "x14068_x": "X14068_X",
  "x14068_x_a": "X14068_X_A",
  "x14068": "X14068_X",
  "credit card debt value": "X14068_X",
  "debt amount": "X14068_X",
  "credit debt value": "X14068_X",
  "outstanding debt": "X14068_X",
  "credit card debt amount": "X14068_X",
  "revolving debt": "X14068_X",
  "consumer debt": "X14068_X",
  "unpaid balance": "X14068_X",
  "debt load": "X14068_X",
  "debt burden": "X14068_X",
  "credit utilization amount": "X14068_X",
  "owed amount": "X14068_X",
  "total debt value": "X14068_X",

  // === GENERATION DEMOGRAPHICS ===
  // Generation Alpha (Born 2017 or Later)
  "generation alpha": "GENALPHACY",
  "gen alpha": "GENALPHACY",
  "genalphacy": "GENALPHACY",
  "alpha generation": "GENALPHACY",
  "youngest generation": "GENALPHACY",
  "born 2017 later": "GENALPHACY",
  "kids": "GENALPHACY",
  "children": "GENALPHACY",
  "toddlers": "GENALPHACY",
  "young children": "GENALPHACY",
  "preschoolers": "GENALPHACY",
  "elementary age": "GENALPHACY",
  "generation alpha percentage": "GENALPHACY_P", 
  "gen alpha percentage": "GENALPHACY_P",
  "alpha percent": "GENALPHACY_P",
  "youngest percent": "GENALPHACY_P",
  "children percentage": "GENALPHACY_P",
  "kids percentage": "GENALPHACY_P",
  
  // Generation Z (Born 1999 to 2016)
  "generation z": "GENZ_CY",
  "gen z": "GENZ_CY",
  "genz": "GENZ_CY",
  "gen z population": "GENZ_CY",
  "z generation": "GENZ_CY",
  "born 1999 2016": "GENZ_CY",
  "teens": "GENZ_CY",
  "teenagers": "GENZ_CY",
  "young adults": "GENZ_CY",
  "zoomers": "GENZ_CY",
  "digital natives": "GENZ_CY",
  "post millennial": "GENZ_CY",
  "generation z percentage": "GENZ_CY_P",
  "gen z percentage": "GENZ_CY_P",
  "genz percentage": "GENZ_CY_P",
  "z percent": "GENZ_CY_P",
  "teens percentage": "GENZ_CY_P",
  "young adult percentage": "GENZ_CY_P",
  "zoomers percentage": "GENZ_CY_P",

  // === LOCATION FIELDS ===
  "latitude": "LATITUDE",
  "lat": "LATITUDE",
  "y coordinate": "LATITUDE",
  "north south": "LATITUDE",
  "longitude": "LONGITUDE",
  "long": "LONGITUDE",
  "lng": "LONGITUDE",
  "x coordinate": "LONGITUDE",
  "east west": "LONGITUDE",
  "address": "address",
  "street address": "address",
  "street": "address",
  "location address": "address",
  "country": "country",
  "nation": "country",
  "country code": "country",
  "locality": "locality",
  "city": "locality",
  "town": "locality",
  "municipality": "locality",
  "local area": "locality",
  "name": "name",
  "place name": "name",
  "location name": "name",
  "poi name": "name",
  "business name": "name",
  "postcode": "postcode",
  "postal code": "postcode",
  "zip": "postcode",
  "zip code field": "postcode",
  "mail code": "postcode",
  "region": "region",
  "state": "region",
  "province": "region",
  "territory": "region",
  "administrative area": "region",

  // === NATURAL LANGUAGE ALIASES ===
  // Population and Demographics
  "population": "GENALPHACY", // Default to gen alpha as primary demographic
  "people": "GENALPHACY",
  "residents": "GENALPHACY",
  "inhabitants": "GENALPHACY",
  "demographics": "GENALPHACY",
  "demographic data": "GENALPHACY",
  "census": "GENALPHACY",
  "headcount": "GENALPHACY",
  "total people": "GENALPHACY",
  
  // Youth and Age-related
  "young": "GENZ_CY_P",
  "younger": "GENZ_CY_P",
  "youth": "GENZ_CY_P",
  "young people": "GENZ_CY_P",
  "youthful": "GENZ_CY_P",
  "millennial": "GENZ_CY_P",
  "next generation": "GENZ_CY_P",
  
  // Financial and Economic
  "wealth": "X14058_X",
  "net worth": "X14058_X",
  "financial assets": "X14058_X",
  "money": "X14060_X",
  "cash": "X14060_X",
  "banking": "MP10020A_B_P",
  "financial": "MP10020A_B_P",
  "financial services": "MP10020A_B_P",
  "fintech": "MP10110A_B_P",
  "payment technology": "MP10110A_B_P",
  "digital finance": "MP10110A_B_P",
  
  // Technology and Digital
  "technology": "MP10110A_B_P",
  "tech": "MP10110A_B_P",
  "digital": "MP10110A_B_P",
  "mobile": "MP10110A_B_P",
  "app users": "MP10110A_B_P",
  "smartphone": "MP10110A_B_P",
  
  // Tax and Accounting
  "tax": "MP10128A_B_P",
  "taxes": "MP10128A_B_P",
  "tax preparation": "MP10128A_B_P",
  "tax filing": "MP10128A_B_P",
  "accountant": "MP10128A_B_P",
  "accounting": "MP10128A_B_P",
  
  // Location and Geography
  "location": "DESCRIPTION",
  "place": "DESCRIPTION",
  "location description": "DESCRIPTION",
  "geographic": "DESCRIPTION",
  "geography": "DESCRIPTION",
  "zip code area": "DESCRIPTION",
  "postal area": "DESCRIPTION"
};

export const fieldAliases = FIELD_ALIASES;